---
title: "SNAP data viz"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE, message=FALSE, warning=FALSE}

library(tidyverse)
library(highcharter)
library(sjlabelled)

source("functionsg.R")

snap_final <- read_rds("data/snap_df3.rds")

# library(showtext)
# font_add_google(name = "Montserrat", family = "Montserrat")
# showtext_auto()


extrafont::loadfonts(quiet = FALSE)

mysource <- "Source: U.S. Department of Agriculture 2024"

```

## Basic Usage Stats
Number of households getting SNAP benefits over time. 
```{r}
options(scipen=999)

# myfont <- list(
#   font = "Montserrat",
#   size = 14
# )


fig_basic <- snap_final %>% 
  filter(state_abbrev == "US") %>% 
  rename("Number of households" = snaphh2, 
         date = ym) %>% 
  ggplot(aes(x=dat, y= `Number of households`))+
  geom_col(alpha = 0.5, fill = nord_silver[5])+
  custom_style3()+
  scale_x_date(name = NULL)+
  scale_y_continuous(name = NULL, 
                   labels = scales::comma)+
  labs(title = "Number of US Households Receiving SNAP Benefits", 
       caption = mysource)

  
plotly::ggplotly(fig_basic) %>% 
  plotly::layout(font = list(family = "Montserrat"), 
                 title = list(x = 0.4,            # x position with respect to `xref` in normalized 
                                        # coordinates from "0" (left) to "1" (right).
                      xanchor ="right"), 
                 xaxis = list(title = ''), 
                 yaxis = list(title = ''), 
                  margin = list(
      l = 0,
      r = 0,
      b = 0,
      t = 40, pad = 1
    ))


snap_final %>% 
  filter(state_abbrev == "US") %>% 
  hchart(., "column",
         hcaes(x = ym, y = snaphh2), 
         color = nord_silver[5], 
         name = "Number of households") %>% 
  hc_title(text = "Number of US Households Receiving SNAP Benefits") %>% 
  hc_xAxis(title = list(text = "")) %>% 
  hc_yAxis(title = list(text = "")) %>% 
  hc_caption(text = "Source: U.S. Department of Agriculture") %>% 
  hc_add_theme(hc_theme_cstm())

```

Benefit amounts over time
```{r}


snap_final %>% 
  filter(state_abbrev == "US") %>% 
  hchart(., "line",
         hcaes(x = ym, y= benperhh), 
         color = nord_silver[5], 
         name = "Benefit amount per household") %>% 
  hc_title(text = "Benefit Amounts per Household") %>% 
  hc_xAxis(title = list(text = "")) %>% 
  hc_yAxis(title = list(text = "")) %>% 
  hc_caption(text = "Source: U.S. Department of Agriculture") %>% 
  hc_add_theme(hc_theme_cstm())











```

